### ISSUE TITLE
Can not build the project

### ISSUE THREAD

**Issue by Corazon-Way** [svkaiser/PowerslaveEX#1]
Can't build the project - some files for external libs are missing. First I had to download files for openal - ..\lib\eaxguid.lib and ..\lib\openal32.lib and now I getting LINK : fatal error LNK1104: cannot open file '.\..\lpng1612\projects\visualc71\Win32_LIB_Debug\libpngd.lib', I can't find any builds with these Win32_*_* folders included, just notes about them.

All of this I'm trying to do on a Vista x64 Virtual Machine with Visual Studio 2008 C++ Express installed. Previously I tried to install VS2008C++E on a Windows 10 x64 VM, but VS2008 were crashing every time I open any file.

**Comment by Corazon-Way** [comment]
My bad. I'm very new to all this. There is a bar at the header where you can choose DLL Debug, LIB Release and more. You should build all of this.

Successfully compiled anubis.exe after compiling all the libraries.

**Comment by PlasticCog** [comment]
Can you go into more detail? I'm getting the same problem but I don't see the part you mention.

**Comment by montycoral** [comment]
hi... i have the same issue but I can't do what you did ... could you send me a guide or post a link to download the files you assembled? i mean this issue ('...\lpng1612\projects\visualc71\Win32_LIB_Debug\libpngd.lib')...  I would be very grateful to you
